# Generated by Django 4.2.1 on 2023-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
